Repository Central-MakeUs/Youngduck-Client, pull requests merged in 2024-01, with the labels that each got.

#6 [UI] 공통 스타일 구현
  src/App.tsx
  src/components/Typography.tsx
  src/styles/colors/another.ts
  src/styles/colors/background.ts
  src/styles/colors/fill.ts
  src/styles/colors/index.ts
  src/styles/colors/line.ts
  src/styles/colors/primary.ts
  src/styles/colors/state.ts
  src/styles/colors/text.ts
  src/styles/texts/index.ts
  src/types/color.ts
  src/types/typography.ts
  src/utils/checkTypographyStyle.ts
Labels: UI

#10 [FEAT] 스플래시 화면 구현
  android/app/src/main/java/com/youngduck/MainActivity.java
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/drawable/splashscreen.xml
  android/app/src/main/res/layout/launch_screen.xml
  ios/Podfile.lock
  ios/Youngduck/AppDelegate.mm
  ios/Youngduck/Images.xcassets/Contents.json
  ios/Youngduck/Images.xcassets/Image 1.imageset/Contents.json
  ios/Youngduck/Images.xcassets/Image 1.imageset/splash.png
  ios/Youngduck/Images.xcassets/Image 1.imageset/splash2.png
  ios/Youngduck/Images.xcassets/Image 1.imageset/splash3.png
  ios/Youngduck/LaunchScreen.storyboard
  package.json
  src/App.tsx
  yarn.lock
Labels: Feature

#16 [REFACTOR] 폴더 구조 수정 및 style 수정
  src/App.tsx
  src/components/button/index.tsx
  src/components/button/kakaoLogin/KakaoLogin.style.ts
  src/components/button/kakaoLogin/index.tsx
  src/components/login/loginContainer/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/login/LoginScreen.style.ts
  src/screens/login/LoginScreen.tsx
Labels: Refactor

#18 [UI] bottomTab 컴포넌트 생성 및 layout 잡기
  .ondevice/storybook.requires.js
  src/App.tsx
  src/assets/images/Bg-login.png
  src/assets/images/popcornmate.png
  src/assets/index.ts
  src/assets/svgIcons/index.tsx
  src/components/button/kakaoLogin/index.tsx
  src/components/container/defaultContainer/DefaultContainer.style.ts
  src/components/container/defaultContainer/index.tsx
  src/components/container/defaultScrollContainer/DefaultScrollContainer.style.ts
  src/components/container/defaultScrollContainer/index.tsx
  src/components/container/loginContainer/LoginContainer.style.ts
  src/components/container/loginContainer/index.tsx
  src/components/profile/Profile.style.ts
  src/components/profile/index.tsx
  src/components/topBar/backMenuTopBar/BackMenuTopBar.stories.tsx
  src/components/topBar/backTitleTopBar/BackTitleTopBar.stories.tsx
  src/components/topBar/backTitleTopBar/BackTitleTopBar.style.ts
  src/components/topBar/backTitleTopBar/index.tsx
  src/components/topBar/menuTopBar/MenuTopBar.stories.tsx
  src/components/topBar/menuTopBar/MenuTopBar.style.ts
  src/components/topBar/menuTopBar/index.tsx
  src/components/topBar/subTitleTopBar/SubTitleTopBar.stories.tsx
  src/components/topBar/subTitleTopBar/SubTitleTopBar.style.ts
  src/components/topBar/subTitleTopBar/index.tsx
  src/components/topBar/textTopBar/TextTopBar.stories.tsx
  src/components/topBar/textTopBar/TextTopBar.style.ts
  src/components/topBar/textTopBar/index.tsx
  src/components/topBar/titleTopBar/TitleTopBar.style.ts
  src/components/topBar/titleTopBar/index.tsx
  src/constants/bottomTabScreens.ts
  src/constants/stackScreens.ts
  src/hooks/useNavigator.ts
  src/navigators/BottomTabNavigator.tsx
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/BottomTabNavigator.style.ts
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/HomeScreen.tsx
  src/screens/home/HomeScreen.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/myPage/MyPageScreen.tsx
  src/screens/popCornParty/PopcornPartyScreen.tsx
  src/screens/screening/ScreeningScreen.tsx
  src/types/navigator.ts
  src/types/ui.ts
  src/types/ui/svgIcons.ts
Labels: UI

#20 [UI] 스크리닝 홈 퍼블리싱
  .ondevice/storybook.requires.js
  src/assets/images/bg-popcornParty.png
  src/assets/images/bg-writeImage.png
  src/assets/index.ts
  src/components/banner/Banner.style.ts
  src/components/banner/index.tsx
  src/components/buttons/boxButton/BoxButton.stories.tsx
  src/components/buttons/boxButton/BoxButton.style.ts
  src/components/buttons/boxButton/index.tsx
  src/components/buttons/kakaoLogin/KakaoLogin.style.ts
  src/components/buttons/kakaoLogin/index.tsx
  src/components/buttons/roundButton/RoundButton.style.ts
  src/components/buttons/roundButton/index.tsx
  src/components/carousel/Carousel.stories.tsx
  src/components/carousel/Carousel.style.ts
  src/components/carousel/index.tsx
  src/components/container/loginContainer/LoginContainer.style.ts
  src/components/container/loginContainer/index.tsx
  src/components/divider/Divider.style.ts
  src/components/divider/index.tsx
  src/components/modal/index.tsx
  src/components/topBar/backTitleTopBar/index.tsx
  src/components/topBar/cancelTopBar/index.tsx
  src/components/topBar/subMenuTopBar/index.tsx
  src/components/topBar/subTitleTopBar/index.tsx
  src/components/topBar/textTopBar/index.tsx
  src/components/topBar/titleTopBar/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/screening/ScreeningScreen.style.ts
  src/screens/screening/ScreeningScreen.tsx
  src/screens/screening/components/recentScreening/RecentScreening.style.ts
  src/screens/screening/components/recentScreening/index.tsx
  src/screens/screening/components/reviewItem/ReviewItem.style.ts
  src/screens/screening/components/reviewItem/index.tsx
  src/screens/screening/components/reviewScreening/ReviewScreening.style.ts
  src/screens/screening/components/reviewScreening/index.tsx
  src/screens/screening/components/weeklyScreening/WeeklyScreening.style.ts
  src/screens/screening/components/weeklyScreening/index.tsx
  src/types/login/index.ts
  src/types/theme/typography.ts
  src/types/ui.ts
  src/utils/getScreenSize.ts
Labels: UI

#23 [UI] 회원가입 스크린 구현
  src/assets/images/Bg-fin.png
  src/assets/images/pacong.png
  src/assets/index.ts
  src/components/buttons/selectButton/SelectedButton.style.ts
  src/components/buttons/selectButton/index.tsx
  src/components/checkBox/index.tsx
  src/components/container/defaultContainer/DefaultContainer.style.ts
  src/components/divider/index.tsx
  src/components/textInput/TextInput.style.ts
  src/components/textInput/index.tsx
  src/components/title/subTitle/SubTitle.stories.tsx
  src/components/title/subTitle/SubTitle.style.ts
  src/components/title/subTitle/index.tsx
  src/components/title/subTitleDescription/SubTitleDescripiton.stories.tsx
  src/components/title/subTitleDescription/SubTitleDescripiton.style.ts
  src/components/title/subTitleDescription/index.tsx
  src/components/topBar/backTopBar/BackTopBar.stories.tsx
  src/components/topBar/backTopBar/BackTopBar.style.ts
  src/components/topBar/backTopBar/index.tsx
  src/constants/stackScreens.ts
  src/hooks/useFocus.ts
  src/hooks/useHandleAgreement.ts
  src/hooks/useNavigator.ts
  src/navigators/StackNavigator.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/screening/ScreeningScreen.tsx
  src/screens/signup/SignupScreen.style.ts
  src/screens/signup/SignupScreen.tsx
  src/screens/signup/components/agreementBottomSheet/Agreement.tsx
  src/screens/signup/components/agreementBottomSheet/index.tsx
  src/screens/signup/components/inputGenre/InputGenre.style.ts
  src/screens/signup/components/inputGenre/TextButtonContainer.tsx
  src/screens/signup/components/inputGenre/index.tsx
  src/screens/signup/components/inputNickname/index.tsx
  src/screens/signup/components/progressBar/ProgressBar.style.ts
  src/screens/signup/components/progressBar/index.tsx
  src/screens/signup/signupComplete/SIgnupCompleteScreen.tsx
  src/screens/signup/signupComplete/SignupCompleteScreen.style.ts
  src/types/navigator.ts
  src/types/signup/agreement.ts
  src/types/signup/genre.ts
  src/types/theme/color.ts
  src/types/ui.ts
  src/utils/moveScreen.ts
  src/utils/selectGenre.ts
Labels: UI

#24 [FEAT] 스크리닝 페이지 stack navigation 생성
  src/App.tsx
  src/components/buttons/roundButton/RoundButton.style.ts
  src/components/buttons/roundButton/index.tsx
  src/components/buttons/selectButton/SelectedButton.style.ts
  src/components/carousel/index.tsx
  src/components/divider/Divider.style.ts
  src/components/divider/index.tsx
  src/components/topBar/cancelTopBar/CancelTopBar.style.ts
  src/constants/screeningStackScreen.ts
  src/constants/stackScreens.ts
  src/hooks/useNavigator.ts
  src/navigators/ScreeningStackNavigator.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/myPage/MyPageScreen.tsx
  src/screens/screening/detail/DetailScreen.style.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/home/HomeScreen.style.ts
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/home/components/recentScreening/RecentScreening.style.ts
  src/screens/screening/home/components/recentScreening/index.tsx
  src/screens/screening/home/components/reviewItem/ReviewItem.style.ts
  src/screens/screening/home/components/reviewItem/index.tsx
  src/screens/screening/home/components/reviewScreening/ReviewScreening.style.ts
  src/screens/screening/home/components/reviewScreening/index.tsx
  src/screens/screening/home/components/weeklyScreening/WeeklyScreening.style.ts
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/screens/screening/reviewWriting/ReviewWritingScreen.style.ts
  src/screens/screening/reviewWriting/ReviewWritingScreen.tsx
  src/screens/screening/screeningList/ScreeningList.style.ts
  src/screens/screening/screeningList/ScreeningList.tsx
  src/screens/screening/writing/WritingScreen.style.ts
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/signup/components/agreementBottomSheet/AgreeBottomSheet.style.ts
  src/screens/signup/components/agreementBottomSheet/index.tsx
  src/types/navigator.ts
Labels: Feature

#27 [RENAME] 폴더 구조 수정
  src/components/inputs/textInput/TextInput.stories.tsx
  src/components/inputs/textInput/TextInput.style.ts
  src/components/inputs/textInput/index.tsx
  src/components/popup/Modal.stories.tsx
  src/components/popup/Modal.style.ts
  src/components/popup/index.tsx
  src/components/progressBar/ProgressBar.style.ts
  src/components/progressBar/index.tsx
  src/components/title/subTitle/SubTitle.style.ts
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/signup/SignupScreen.tsx
  src/screens/signup/components/inputNickname/index.tsx
  src/screens/signupComplete/SIgnupCompleteScreen.tsx
  src/screens/signupComplete/SignupCompleteScreen.style.ts
Labels: Rename

#28 [UI] 팝콘파티 홈 퍼블리싱
  ios/Podfile.lock
  src/assets/svgIcons/index.tsx
  src/components/buttons/boxButton/index.tsx
  src/components/cards/popcornTrendingCard/PopcornTrendingCard.style.ts
  src/components/cards/popcornTrendingCard/index.tsx
  src/components/chip/Chip.style.ts
  src/components/chip/index.tsx
  src/components/items/popcornItem/PopcornItem.style.ts
  src/components/items/popcornItem/index.tsx
  src/components/popup/index.tsx
  src/components/topBar/backTitleTopBar/BackTitleTopBar.style.ts
  src/components/topBar/backTitleTopBar/index.tsx
  src/components/topBar/backTopBar/BackTopBar.style.ts
  src/components/topBar/backTopBar/index.tsx
  src/components/topBar/cancelTopBar/CancelTopBar.style.ts
  src/components/topBar/cancelTopBar/index.tsx
  src/components/topBar/subMenuTopBar/SubMenuTopBar.style.ts
  src/components/topBar/subMenuTopBar/index.tsx
  src/components/topBar/textTopBar/TextTopBar.style.ts
  src/components/topBar/textTopBar/index.tsx
  src/components/topBar/titleTopBar/TitleTopBar.style.ts
  src/components/topBar/titleTopBar/index.tsx
  src/components/typography/index.tsx
  src/components/vote/index.tsx
  src/constants/bottomTabScreens.ts
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/popCornParty/PopcornPartyScreen.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/home/components/otherPopcorns/index.tsx
  src/screens/popCornParty/home/components/trendingMovie/index.tsx
  src/screens/popCornParty/home/components/trendingPopcorn/index.tsx
  src/screens/popCornParty/home/components/voteNextPopcorn/index.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeReview/WriteReviewScreen.tsx
  src/screens/screening/home/components/recentScreening/index.tsx
  src/screens/screening/home/components/reviewItem/index.tsx
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/types/navigator.ts
  src/types/popcornParty/index.ts
  src/types/ui.ts
Labels: UI

#30 [UI] 스크리닝 등록하기 페이지 퍼블리싱
  package.json
  src/assets/icons/calendar.svg
  src/assets/icons/down-arrow.svg
  src/assets/icons/gallery.svg
  src/assets/icons/location.svg
  src/assets/icons/time.svg
  src/assets/icons/top-arrow.svg
  src/components/buttons/roundButton/RoundButton.style.ts
  src/components/buttons/roundButton/index.tsx
  src/components/dismissKeyboardView/index.tsx
  src/components/inputs/buttonInput/ButtonInput.style.ts
  src/components/inputs/buttonInput/index.tsx
  src/components/inputs/textArea/TextArea.style.ts
  src/components/inputs/textArea/index.tsx
  src/components/inputs/textInput/index.tsx
  src/components/modals/dateRangePickerModal/DateRangePickerModal.style.ts
  src/components/modals/dateRangePickerModal/index.tsx
  src/components/modals/timePickerModal/TimePickerModal.style.ts
  src/components/modals/timePickerModal/index.tsx
  src/components/select/Select.style.ts
  src/components/select/index.tsx
  src/constants/screeningStackScreen.ts
  src/constants/stackScreens.ts
  src/navigators/ScreeningStackNavigator.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/navigators/stackNavigator/ScreeningStackNavigator.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/writing/WritingScreen.style.ts
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/screening/writing/components/screeningGallery/ScreeningGallery.style.ts
  src/screens/screening/writing/components/screeningGallery/index.tsx
  src/styles/Input.style.ts
  src/types/navigator.ts
  yarn.lock
Labels: UI

#32 [UI] 팝콘파티 팝콘작 추천 목록 퍼블리싱
  src/components/items/popcornItem/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/home/components/otherPopcorns/index.tsx
  src/screens/popCornParty/home/components/trendingMovie/index.tsx
  src/screens/popCornParty/home/components/trendingPopcorn/index.tsx
  src/screens/popCornParty/home/components/voteNextPopcorn/index.tsx
  src/screens/popCornParty/home/dummy.ts
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/screens/popCornParty/recommandList/dummy.ts
  src/types/popcornParty/index.ts
Labels: UI

#33 [REFACTOR] Input 컴포넌트 리팩토링
  src/components/buttons/duplicatedButton/DuplicatedButton.style.ts
  src/components/buttons/duplicatedButton/index.tsx
  src/components/input/index.tsx
  src/components/inputs/buttonInput/ButtonInput.style.ts
  src/components/inputs/buttonInput/index.tsx
  src/components/inputs/textArea/TextArea.style.ts
  src/components/inputs/textArea/index.tsx
  src/components/inputs/textInput/TextInput.stories.tsx
  src/components/inputs/textInput/TextInput.style.ts
  src/components/inputs/textInput/index.tsx
  src/components/select/index.tsx
  src/components/topBar/backTitleTopBar/BackTitleTopBar.style.ts
  src/components/topBar/backTopBar/BackTopBar.style.ts
  src/components/topBar/cancelTopBar/CancelTopBar.style.ts
  src/components/topBar/subMenuTopBar/SubMenuTopBar.style.ts
  src/components/topBar/textTopBar/TextTopBar.style.ts
  src/components/topBar/titleTopBar/TitleTopBar.style.ts
  src/hooks/useFocus.ts
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/signup/components/inputNickname/index.tsx
  src/styles/Input.style.ts
  src/types/ui.ts
Labels: Refactor

#35 [FEAT] 애플 로그인
  ios/Podfile.lock
  ios/Youngduck.xcodeproj/project.pbxproj
  ios/Youngduck/Info.plist
  ios/Youngduck/Youngduck.entitlements
  package.json
  src/assets/icons/apple-logo.svg
  src/components/auth/apple/AppleLogin.style.ts
  src/components/auth/apple/index.tsx
  src/components/auth/kakao/KakaoLogin.style.ts
  src/components/auth/kakao/index.tsx
  src/components/buttons/kakaoLogin/index.tsx
  src/screens/login/LoginScreen.tsx
  yarn.lock
Labels: Feature

#38 [UI] 팝콘작 추천 작성 퍼블리싱
  src/assets/icons/search.svg
  src/components/buttons/searchButton/index.tsx
  src/components/input/index.tsx
  src/components/inputs/buttonInput/index.tsx
  src/components/inputs/textArea/index.tsx
  src/components/items/movieItem/MovieItem.style.ts
  src/components/items/movieItem/index.tsx
  src/components/typography/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.style.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/SearchBottomSheet.style.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/dummy.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/types/theme/typography.ts
  src/utils/getVoteDateRange.ts
Labels: UI

#39 [FEAT] 카카오 장소 검색 기능 구현
  package.json
  src/components/inputs/buttonInput/index.tsx
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/screens/screening/kakaoSearch/KakaoSearchScreen.style.ts
  src/screens/screening/kakaoSearch/KakaoSearchScreen.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/stores/location.ts
  src/types/navigator.ts
  yarn.lock
Labels: Feature

#40 [FEAT] 갤러리 권한 및 갤러리 이미지 업로드
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Youngduck/Info.plist
  package.json
  src/screens/screening/writing/components/screeningGallery/index.tsx
  src/utils/checkPermission.ts
  yarn.lock
Labels: Feature

#50 [REFACTOR] 갤러리 접근 및 이미지 업로드 로직 리팩토링
  src/screens/screening/writing/components/screeningGallery/index.tsx
  src/utils/checkPermission.ts
Labels: Refactor

#46 [REFACTOR] progress bar 리팩토링
  src/components/progressBar/index.tsx
  src/screens/signup/SignupScreen.tsx
  src/utils/moveScreen.ts
Labels: Refactor

#51 [FEAT] axios interceptor 로직 구현 및 토큰 스토리지 저장
  package.json
  src/App.tsx
  src/apis/.gitkeep
  src/apis/auth/auth.ts
  src/apis/auth/social.ts
  src/apis/index.ts
  src/apis/social.ts
  src/apis/user.ts
  src/assets/.gitkeep
  src/components/.gitkeep
  src/components/auth/kakao/index.tsx
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/models/.gitkeep
  src/models/auth/entity/index.ts
  src/models/auth/request/index.ts
  src/models/auth/response/index.ts
  src/models/common/responseDTO.ts
  src/models/user/entity/loginType.ts
  src/models/user/request/registerLoginBody.ts
  src/navigators/.gitkeep
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/.gitkeep
  src/screens/signup/SignupScreen.tsx
  src/screens/signup/components/agreementBottomSheet/index.tsx
  src/screens/signup/components/inputGenre/index.tsx
  src/screens/signup/components/inputNickname/index.tsx
  src/services/.gitkeep
  src/services/localStorage/localStorage.ts
  src/services/localStorage/localStorageKey.ts
  src/stores/.gitkeep
  src/stores/user.ts
  src/styles/.gitkeep
  src/utils/.gitkeep
  yarn.lock
Labels: Feature

#53 [FEAT] 이미지 업로드, 스크리닝 작성하기 api 연결
  package.json
  src/apis/image/image.ts
  src/apis/screening/screening.ts
  src/components/input/index.tsx
  src/components/inputs/buttonInput/index.tsx
  src/components/select/index.tsx
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/image/request/index.ts
  src/models/screening/request/index.ts
  src/models/screening/response/index.ts
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/kakaoSearch/KakaoSearchScreen.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/screening/writing/components/screeningGallery/ScreeningGallery.style.ts
  src/screens/screening/writing/components/screeningGallery/index.tsx
  src/stores/location.ts
  src/types/navigator.ts
  src/utils/getDate.ts
  src/utils/getVoteDateRange.ts
  yarn.lock
Labels: Feature

#56 [UI] 팝콘작 상세 퍼블리싱
  ios/Podfile.lock
  src/assets/icons/disappointed.svg
  src/assets/icons/satisfied.svg
  src/assets/icons/tooltip.svg
  src/assets/images/profile1.png
  src/assets/index.ts
  src/components/buttons/boxButton/index.tsx
  src/components/items/commentItem/CommentItem.style.ts
  src/components/items/commentItem/index.tsx
  src/components/profile/Profile.style.ts
  src/components/profile/index.tsx
  src/components/screeningIndex/ScreeningIndex.style.ts
  src/components/screeningIndex/index.tsx
  src/components/screeningIndex/reviewRate/ReviewRate.style.ts
  src/components/screeningIndex/reviewRate/index.tsx
  src/components/screeningIndex/tooltip/Tooltip.style.ts
  src/components/screeningIndex/tooltip/index.tsx
  src/components/tabBar/TabBar.style.ts
  src/components/tabBar/index.tsx
  src/components/topBar/backTitleTopBar/BackTitleTopBar.style.ts
  src/components/topBar/backTitleTopBar/index.tsx
  src/components/typography/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/detail/popcornKeyword/PopcornKeyword.style.ts
  src/screens/popCornParty/detail/popcornKeyword/index.tsx
  src/screens/popCornParty/detail/popcornPartyDetailScreen.style.ts
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/home/components/voteNextPopcorn/index.tsx
Labels: UI

#54 [UI] 팝콘작 리뷰하기 퍼블리싱
  src/components/buttons/boxButton/BoxButton.style.ts
  src/components/buttons/multibutton/MultiButton.style.ts
  src/components/buttons/multibutton/index.tsx
  src/components/buttons/selectButton/index.tsx
  src/components/container/imageContentScrollContainer/imageContentScrollContainer.style.ts
  src/components/container/imageContentScrollContainer/index.tsx
  src/components/items/keywordItem/KeywordItem.style.ts
  src/components/items/keywordItem/index.tsx
  src/components/progressBar/index.tsx
  src/components/screeningRate/ScreeningRate.style.ts
  src/components/screeningRate/index.tsx
  src/components/screeningRate/reviewRate/ReviewRate.style.ts
  src/components/screeningRate/reviewRate/index.tsx
  src/components/tabBar/TabBar.style.ts
  src/components/tooltip/Tooltip.style.ts
  src/components/tooltip/index.tsx
  src/components/topBar/backCancelTopBar/BackCancelTopBar.style.ts
  src/components/topBar/backCancelTopBar/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/detail/popcornKeyword/index.tsx
  src/screens/popCornParty/writeReview/WriteReviewScreen.style.ts
  src/screens/popCornParty/writeReview/WriteReviewScreen.tsx
  src/screens/popCornParty/writeReview/reviewTarget/ReviewTarget.style.ts
  src/screens/popCornParty/writeReview/reviewTarget/index.tsx
  src/screens/popCornParty/writeReview/selectReview/SelectReview.style.ts
  src/screens/popCornParty/writeReview/selectReview/index.tsx
  src/screens/popCornParty/writeReview/startReview/StartReview.style.ts
  src/screens/popCornParty/writeReview/startReview/index.tsx
  src/screens/signup/SignupScreen.tsx
  src/utils/getQuestions.ts
  src/utils/moveScreen.ts
Labels: UI

#57 [UI] 스크리닝 목록 페이지 퍼블리싱
  src/components/buttons/searchButton/index.tsx
  src/components/input/index.tsx
  src/components/items/screeningItem/ScreeningItem.style.ts
  src/components/items/screeningItem/index.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/screeningList/ScreeningList.style.ts
  src/screens/screening/screeningList/ScreeningList.tsx
  src/screens/screening/screeningList/components/dateOption/DateOption.style.ts
  src/screens/screening/screeningList/components/dateOption/index.tsx
  src/screens/screening/screeningList/components/screeningFilterList/index.tsx
Labels: UI

#61 [UI] 마이페이지 퍼블리싱
  ios/Podfile.lock
  src/assets/images/my-page1.png
  src/assets/images/my-page2.png
  src/assets/images/my-page3.png
  src/assets/index.ts
  src/assets/svgIcons/index.tsx
  src/components/container/gradientContainer/GradientContainer.style.ts
  src/components/input/index.tsx
  src/components/screeningIndex/ScreeningIndex.style.ts
  src/components/screeningIndex/index.tsx
  src/components/screeningIndex/reviewRate/ReviewRate.style.ts
  src/components/screeningIndex/reviewRate/index.tsx
  src/components/screeningIndex/tooltip/Tooltip.style.ts
  src/components/screeningIndex/tooltip/index.tsx
  src/components/screeningRate/index.tsx
  src/components/topBar/subMenuTopBar/index.tsx
  src/screens/login/LoginScreen.style.ts
  src/screens/myPage/MyPageScreen.style.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/changeNickname/ChangeNicknameScreen.style.ts
  src/screens/myPage/changeNickname/ChangeNicknameScreen.tsx
  src/screens/myPage/components/management/Management.style.ts
  src/screens/myPage/components/management/index.tsx
  src/screens/myPage/components/myScreening/MyScreening.style.ts
  src/screens/myPage/components/myScreening/index.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/signup/components/inputNickname/index.tsx
  src/types/navigator.ts
Labels: UI

#62 [UI] 스크리닝 상세 페이지 퍼블리싱
  package.json
  src/assets/icons/black-ticket.svg
  src/assets/icons/call.svg
  src/assets/icons/close-eye.svg
  src/assets/icons/mail.svg
  src/assets/icons/open-eye.svg
  src/assets/icons/white-ticket.svg
  src/assets/images/profile-1.png
  src/assets/images/profile-2.png
  src/assets/images/profile-3.png
  src/assets/index.ts
  src/assets/svgIcons/index.tsx
  src/components/bottomButton/BottomButton.style.ts
  src/components/bottomButton/index.tsx
  src/components/buttons/optionButton/OptionButton.style.ts
  src/components/buttons/optionButton/index.tsx
  src/components/container/defaultContainer/DefaultContainer.style.ts
  src/constants/tabScreens.ts
  src/screens/screening/detail/DetailScreen.style.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/components/bottomDetailButton/BottomDetailButton.style.ts
  src/screens/screening/detail/components/bottomDetailButton/bottomDetailButton.tsx
  src/screens/screening/detail/components/bottomDetailButton/bottomOptionDetailButton.tsx
  src/screens/screening/detail/components/bottomDetailButton/index.ts
  src/screens/screening/detail/components/detailInfo/index.tsx
  src/screens/screening/detail/components/detailInfoPhone/DetailInfoPhone.style.ts
  src/screens/screening/detail/components/detailInfoPhone/index.tsx
  src/screens/screening/detail/components/detailPositivePlus/index.tsx
  src/screens/screening/detail/components/detailTitle/DetailTitle.style.ts
  src/screens/screening/detail/components/detailTitle/index.tsx
  src/screens/screening/detail/tabs/detailInfoScreen/DetailInfoScreen.style.ts
  src/screens/screening/detail/tabs/detailInfoScreen/DetailInfoScreen.tsx
  src/screens/screening/detail/tabs/detailReviewScreen/DetailReviewScreen.style.ts
  src/screens/screening/detail/tabs/detailReviewScreen/DetailReviewScreen.tsx
  src/screens/screening/detail/tabs/detailStatisticScreen/DetailStatisticScreen.style.ts
  src/screens/screening/detail/tabs/detailStatisticScreen/DetailStatisticScreen.tsx
  src/types/ui.ts
  yarn.lock
Labels: UI

#64 [UI] 스크리닝 리뷰 작성 페이지 퍼블리싱
  src/components/buttonGroups/selectMultipleButtons/SelectMultipleButtons.style.ts
  src/components/buttonGroups/selectMultipleButtons/index.tsx
  src/components/buttonGroups/selectTwoButtons/index.tsx
  src/components/buttonGroups/selectTwoButtons/selectTwoButtons.tyle.ts
  src/components/buttons/selectButton/SelectedButton.style.ts
  src/components/buttons/selectButton/index.tsx
  src/components/cards/agreeNoticeCard/NoticeCard.style.ts
  src/components/cards/agreeNoticeCard/index.tsx
  src/components/inputs/textArea/index.tsx
  src/constants/review.ts
  src/screens/screening/reviewWriting/ReviewWritingScreen.style.ts
  src/screens/screening/reviewWriting/ReviewWritingScreen.tsx
  src/screens/screening/reviewWriting/tabs/ScreeningReview.style.ts
  src/screens/screening/reviewWriting/tabs/endReview/index.tsx
  src/screens/screening/reviewWriting/tabs/firstReview/index.tsx
  src/screens/screening/reviewWriting/tabs/selectReview/index.tsx
  src/utils/getReview.ts
Labels: UI

#69 [FIX] merge 후 지워지지 않은 부분 해결
  src/screens/login/LoginScreen.tsx
Labels: Fix

#72 [UI] 마이페이지 설정 퍼블리싱
  src/components/buttons/boxButton/BoxButton.style.ts
  src/components/buttons/multibutton/index.tsx
  src/components/container/imageContentScrollContainer/imageContentScrollContainer.style.ts
  src/components/container/imageContentScrollContainer/index.tsx
  src/components/subMenu/SubMenu.style.ts
  src/components/subMenu/index.tsx
  src/components/switch/index.tsx
  src/components/title/subTitleDescription/index.tsx
  src/components/topBar/backTitleTopBar/BackTitleTopBar.style.ts
  src/components/topBar/titleCenterTopBar/TitleCenterTopBar.style.ts
  src/components/topBar/titleCenterTopBar/index.tsx
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/screens/myPage/MyPageScreen.style.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/changeNickname/ChangeNicknameScreen.style.ts
  src/screens/myPage/changeNickname/ChangeNicknameScreen.tsx
  src/screens/myPage/setting/SettingScreen.style.ts
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/myPage/setting/screens/agreement/AgreementScreen.tsx
  src/screens/myPage/setting/screens/withdraw/WithdrawScreen.tsx
  src/types/navigator.ts
  src/types/react-native-config.d.ts
  src/types/ui.ts
Labels: UI

#70 [FEAT] 스크리닝 홈페이지 api 연결
  src/apis/screening/screening.ts
  src/assets/icons/chat.svg
  src/assets/images/empty-card.png
  src/assets/images/empty.png
  src/assets/index.ts
  src/components/cards/emptyCard/EmptyCard.style.ts
  src/components/cards/emptyCard/index.tsx
  src/components/carousel/index.tsx
  src/components/items/emptyItem/EmptyItem.style.ts
  src/components/items/emptyItem/index.tsx
  src/components/items/screeningItem/index.tsx
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/screening/request/index.ts
  src/models/screening/response/index.ts
  src/screens/screening/home/HomeScreen.style.ts
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/home/components/reviewItem/ReviewItem.style.ts
  src/screens/screening/home/components/reviewItem/index.tsx
  src/screens/screening/home/components/reviewScreening/index.tsx
  src/screens/screening/home/components/reviewScreeningCarousel/ReviewScreening.style.ts
  src/screens/screening/home/components/reviewScreeningCarousel/index.tsx
  src/screens/screening/home/components/weeklyScreening/WeeklyScreening.style.ts
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/utils/getCategory.ts
  src/utils/getDate.ts
Labels: Feature

#73 [FEAT] 로그인 후 회원가입 이동 로직 수정
  src/apis/auth/auth.ts
  src/components/auth/kakao/index.tsx
  src/navigators/StackNavigator.tsx
Labels: Feature

#75 [UI] 마이페이지 스크리닝 관리 퍼블리싱
  src/assets/svgIcons/index.tsx
  src/components/items/myManagementItem/MyManagementItem.style.ts
  src/components/items/myManagementItem/index.tsx
  src/components/typography/index.tsx
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/components/manageReview/ManageReview.style.ts
  src/screens/myPage/components/manageReview/index.tsx
  src/screens/myPage/components/myScreening/index.tsx
  src/screens/myPage/manageScreening/ManageScreeningScreen.style.ts
  src/screens/myPage/manageScreening/ManageScreeningScreen.tsx
  src/screens/myPage/manageScreening/dummy.ts
  src/types/navigator.ts
  src/types/theme/typography.ts
Labels: UI

#78 [FEAT] 알람 초기 세팅 및 FCM 알람 기능
  .gitignore
  android/app/build.gradle
  android/app/src/debug/java/com/popcornmate/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/popcornmate/MainActivity.java
  android/app/src/main/java/com/popcornmate/MainApplication.java
  android/app/src/main/res/values/colors.xml
  android/app/src/release/java/com/popcornmate/ReactNativeFlipper.java
  android/build.gradle
  android/gradlew
  android/gradlew.bat
  firebase.json
  ios/Podfile
  ios/Podfile.lock
  ios/Youngduck.xcodeproj/project.pbxproj
  ios/Youngduck.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Youngduck.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  ios/Youngduck/AppDelegate.mm
  ios/Youngduck/Info.plist
  ios/Youngduck/Youngduck.entitlements
  package.json
  src/App.tsx
  src/navigators/StackNavigator.tsx
  src/services/alarmService.ts
  yarn.lock
Labels: Feature

#83 [UI] 마이페이지 나의 스크리닝 퍼블리싱
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/myScreening/MyScreeningScreen.style.ts
  src/screens/myPage/myScreening/MyScreeningScreen.tsx
  src/screens/myPage/myScreening/dummy.ts
Labels: UI

#86 [UI] 팝콘파티 팝콘지수 퍼블리싱
  src/components/rates/popcornRate/PopcornRate.style.ts
  src/components/rates/popcornRate/index.tsx
  src/components/rates/reviewRate/ReviewRate.style.ts
  src/components/rates/reviewRate/index.tsx
  src/components/rates/screeningRate/ScreeningRate.style.ts
  src/components/rates/screeningRate/index.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
Labels: UI

#88 [FEAT] 스크리닝 필터링 및 검색 api 연동
  src/apis/screening/screening.ts
  src/assets/images/empty-list.png
  src/assets/index.ts
  src/components/buttons/selectButton/index.tsx
  src/components/items/emptyItem/index.tsx
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/enums/category.ts
  src/models/enums/time.ts
  src/models/screening/request/index.ts
  src/models/screening/response/index.ts
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/screens/screening/screeningList/ScreeningList.tsx
  src/screens/screening/screeningList/components/screeningFilterList/index.tsx
  src/screens/screening/screeningList/components/screeningSearchList/ScreeningSearchList.style.ts
  src/screens/screening/screeningList/components/screeningSearchList/index.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/utils/getCategory.ts
  src/utils/getInfiniteQueryArray.ts
Labels: Feature

#90 [FEAT] 스크리닝 디테일, 리뷰, 리뷰 작성하기 api 연동
  src/apis/screening/detail.ts
  src/apis/screening/list.ts
  src/apis/screening/review.ts
  src/apis/screening/screening.ts
  src/components/bottomButton/bottomBoxButton/BottomBoxButton.style.ts
  src/components/bottomButton/bottomBoxButton/index.tsx
  src/components/bottomButton/bottomOptionButton/BottomOptionButton.style.ts
  src/components/bottomButton/bottomOptionButton/index.tsx
  src/components/buttonGroups/selectTwoButtons/index.tsx
  src/components/buttons/optionButton/OptionButton.style.ts
  src/components/carousel/index.tsx
  src/components/items/emptyItem/EmptyItem.style.ts
  src/components/items/emptyItem/index.tsx
  src/components/items/myManagementItem/index.tsx
  src/constants/review.ts
  src/constants/tabBars.ts
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/enums/review.ts
  src/models/screening/request/index.ts
  src/models/screening/request/listRequestDto.ts
  src/models/screening/request/reviewRequestDto.ts
  src/models/screening/request/screeningRequestDto.ts
  src/models/screening/response/detailResponseDto.ts
  src/models/screening/response/index.ts
  src/models/screening/response/listResponseDto.ts
  src/models/screening/response/reviewResponseDto.ts
  src/models/screening/response/screeningResponseDto.ts
  src/screens/screening/detail/DetailScreen.style.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/components/bottomDetailButton/BottomDetailButton.style.ts
  src/screens/screening/detail/components/bottomDetailButton/bottomDetailButton.tsx
  src/screens/screening/detail/components/bottomDetailButton/bottomOptionDetailButton.tsx
  src/screens/screening/detail/components/bottomDetailButton/index.ts
  src/screens/screening/detail/components/bottomDetailButton/index.tsx
  src/screens/screening/detail/components/detailTitle/index.tsx
  src/screens/screening/detail/tabs/detailInfoScreen/DetailInfoScreen.style.ts
  src/screens/screening/detail/tabs/detailInfoScreen/DetailInfoScreen.tsx
  src/screens/screening/detail/tabs/detailReviewScreen/DetailReviewScreen.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/home/components/reviewItem/index.tsx
  src/screens/screening/home/components/reviewScreeningCarousel/index.tsx
  src/screens/screening/myDetail/MyDetailScreen.tsx
  src/screens/screening/myDetail/components/myDetailBottomButton/index.tsx
  src/screens/screening/reviewWriting/ReviewWritingScreen.tsx
  src/screens/screening/reviewWriting/tabs/endReview/index.tsx
  src/screens/screening/reviewWriting/tabs/firstReview/index.tsx
  src/screens/screening/reviewWriting/tabs/selectReview/index.tsx
  src/screens/screening/screeningList/components/screeningSearchList/index.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/types/navigator.ts
  src/types/ui.ts
Labels: Feature

#91 [FEAT] 팝콘파티 팝콘작 추천 작성 API 연동
  ios/Podfile.lock
  ios/Youngduck.xcodeproj/project.pbxproj
  ios/Youngduck/Info.plist
  src/apis/popcornParty/index.ts
  src/assets/icons/gray-popcorn.svg
  src/components/items/movieItem/index.tsx
  src/hooks/mutaions/useRecommendMovieMutation.ts
  src/models/popcornParty/reponse/index.ts
  src/models/popcornParty/request/index.ts
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/home/components/otherPopcorns/index.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/SearchBottomSheet.style.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/dummy.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/types/popcornParty/index.ts
  src/types/react-native-config.d.ts
  src/utils/formatString.ts
  src/utils/getMovieList.ts
Labels: Feature

#92 [FEAT] 디테일 하단 버튼 로직 생성 및 찜 api 연동
  package.json
  src/apis/screening/detail.ts
  src/components/popup/Popup.style.ts
  src/components/popup/index.tsx
  src/components/snackBar/SnackBar.style.ts
  src/components/snackBar/index.tsx
  src/constants/stackScreens.ts
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/screening/response/detailResponseDto.ts
  src/navigators/Navigator.tsx
  src/navigators/StackNavigator.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/components/bottomDetailButton/index.tsx
  src/screens/screening/detail/hooks/useScreeningType.ts
  src/screens/screening/detail/tabs/detailInfoScreen/DetailInfoScreen.tsx
  src/screens/screening/detail/tabs/detailReviewScreen/DetailReviewScreen.tsx
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/stores/webview.ts
  src/types/navigator.ts
  src/utils/getDate.ts
  src/utils/getInfiniteQueryArray.ts
  src/utils/showSnackBar.ts
  yarn.lock
Labels: Feature

#94 [FEAT] 팝콘파티 홈 API 연동
  ios/Youngduck.xcodeproj/project.pbxproj
  src/apis/popcornParty/index.ts
  src/apis/popcornParty/recommendList/recommendList.ts
  src/components/cards/popcornTrendingCard/PopcornTrendingCard.style.ts
  src/components/cards/popcornTrendingCard/index.tsx
  src/components/items/myManagementItem/index.tsx
  src/components/items/popcornItem/PopcornItem.style.ts
  src/components/items/popcornItem/index.tsx
  src/components/typography/index.tsx
  src/hooks/mutaions/useRecommendMovie.ts
  src/models/popcornParty/reponse/index.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/home/components/otherPopcorns/index.tsx
  src/screens/popCornParty/home/components/trendingMovie/index.tsx
  src/screens/popCornParty/home/components/trendingPopcorn/index.tsx
  src/screens/popCornParty/home/components/voteNextPopcorn/index.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/types/theme/typography.ts
Labels: Feature

#96 [FEAT] 스크리닝 상영지수 및 댓글 신고 api 연동, 댓글 리스트 로직 추가
  src/apis/screening/review.ts
  src/components/items/commentItem/index.tsx
  src/components/loading/Loading.style.ts
  src/components/loading/index.tsx
  src/components/pages/loadingPage/LoadingPage.style.ts
  src/components/pages/loadingPage/index.tsx
  src/components/popup/index.tsx
  src/constants/review.ts
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/screening/response/reviewResponseDto.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/tabs/detailReviewScreen/DetailReviewScreen.style.ts
  src/screens/screening/detail/tabs/detailReviewScreen/DetailReviewScreen.tsx
  src/screens/screening/detail/tabs/detailReviewScreen/components/detailScreeningRate/index.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/screeningList/components/screeningSearchList/index.tsx
Labels: Feature

#99 [FEAT] 내가 작성한 페이지 비공개, 수정, 디테일 api 연동
  src/apis/screening/detail.ts
  src/apis/screening/screening.ts
  src/components/inputs/buttonInput/index.tsx
  src/components/modals/dateRangePickerModal/index.tsx
  src/constants/stackScreens.ts
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/screening/request/screeningRequestDto.ts
  src/models/screening/response/detailResponseDto.ts
  src/navigators/StackNavigator.tsx
  src/screens/screening/myDetail/MyDetailScreen.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/types/navigator.ts
Labels: Feature

#101 [FIX] 스크리닝 query문 머지 충돌 해결
  src/hooks/mutaions/useScreeningMutation.ts
Labels: Fix

#103 [FEAT] 내가 작성한 페이지 통계 api 연동
  src/apis/screening/detail.ts
  src/components/cards/screeningRateCard/index.tsx
  src/components/items/myManagementItem/index.tsx
  src/components/pages/detailInfoPage/DetailInfoPage.style.ts
  src/components/pages/detailInfoPage/components/detailContact/DetailContact.style.ts
  src/components/pages/detailInfoPage/components/detailContact/index.tsx
  src/components/pages/detailInfoPage/components/detailInfo/index.tsx
  src/components/pages/detailInfoPage/index.tsx
  src/components/pages/detailReviewPage/DetailReviewPage.style.ts
  src/components/pages/detailReviewPage/index.tsx
  src/components/pages/detailStatisticPage/DetailStatisticPage.style.ts
  src/components/pages/detailStatisticPage/component/detailPlusList/index.tsx
  src/components/pages/detailStatisticPage/index.tsx
  src/components/title/screeningTitle/ScreeningTitle.ts
  src/components/title/screeningTitle/index.tsx
  src/constants/review.ts
  src/models/enums/review.ts
  src/models/screening/response/detailResponseDto.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/components/detailPositivePlus/index.tsx
  src/screens/screening/detail/tabs/detailStatisticScreen/DetailStatisticScreen.tsx
  src/screens/screening/myDetail/MyDetailScree.style.ts
  src/screens/screening/myDetail/MyDetailScreen.tsx
Labels: Feature

#102 [FEAT] 팝콘파티 상세 API 연동
  src/apis/popcornParty/detail/detail.ts
  src/apis/popcornParty/index.ts
  src/apis/popcornParty/writeReview/writeReview.ts
  src/assets/index.ts
  src/components/container/imageContentScrollContainer/index.tsx
  src/components/items/commentItem/index.tsx
  src/components/items/keywordItem/index.tsx
  src/components/popcornKeyword/PopcornKeyword.style.ts
  src/components/popcornKeyword/index.tsx
  src/components/profile/index.tsx
  src/components/rates/screeningRate/index.tsx
  src/hooks/mutaions/useMovieReviewMutation.ts
  src/hooks/mutaions/usePopcornPartyMutation.ts
  src/models/popcornParty/reponse/index.ts
  src/models/popcornParty/request/index.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/detail/components/detailBottomButtons/DetailBottomButtons.tsx
  src/screens/popCornParty/detail/components/detailMovie/DetailPopcorn.style.ts
  src/screens/popCornParty/detail/components/detailMovie/DetailPopcorn.tsx
  src/screens/popCornParty/detail/popcornKeyword/index.tsx
  src/screens/popCornParty/detail/popcornPartyDetailScreen.style.ts
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/writeReview/WriteReviewScreen.tsx
  src/screens/popCornParty/writeReview/selectReview/index.tsx
  src/screens/popCornParty/writeReview/startReview/index.tsx
  src/types/navigator.ts
  src/utils/getKeyword.ts
  src/utils/getQuestions.ts
  src/utils/getWeekOfMonth.ts
Labels: Feature
