Repository Central-MakeUs/Youngduck-Client, pull requests merged in 2024-02, with the labels that each got.

#106 [FEAT] 갤러리 권한 로직 수정 및 알람 권한 on/off 추가(android)
  ios/Podfile
  ios/Podfile.lock
  src/apis/auth/auth.ts
  src/apis/index.ts
  src/components/pages/detailInfoPage/index.tsx
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/enums/permission.ts
  src/models/screening/request/screeningRequestDto.ts
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/reviewWriting/tabs/endReview/index.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/screening/writing/components/screeningGallery/index.tsx
  src/services/localStorage/localStorage.ts
  src/services/localStorage/localStorageKey.ts
  src/services/permissionAlert.ts
  src/services/permissionService.ts
  src/utils/checkPermission.ts
Labels: Feature

#109 [FIX] 상영회 등록하기 수정하기 오류 해결
  src/components/inputs/buttonInput/index.tsx
  src/components/pages/detailReviewPage/index.tsx
  src/hooks/mutaions/useScreeningMutation.ts
  src/navigators/bottomTabNavigator/BottomTabNavigator.style.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/myDetail/MyDetailScreen.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/screening/writing/hooks/useHandleInput.ts
Labels: Fix

#110 [FEAT] 마이페이지 스크리닝 관리 API 연동
  src/apis/myPage/index.ts
  src/components/items/myManagementItem/index.tsx
  src/hooks/mutaions/useManageScreeningMutation.ts
  src/models/myPage/response/index.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/manageScreening/ManageScreeningScreen.tsx
  src/screens/myPage/manageScreening/dummy.ts
  src/types/navigator.ts
  src/utils/getDate.ts
Labels: Feature

#114 [FIX] 1차 QA UI 피드백 반영
  ios/Podfile
  ios/Podfile.lock
  ios/Youngduck.xcodeproj/project.pbxproj
  ios/Youngduck.xcodeproj/xcshareddata/xcschemes/Youngduck.xcscheme
  src/apis/popcornParty/detail/detail.ts
  src/assets/icons/gray-popcorn.svg
  src/assets/images/empty-large.png
  src/assets/images/empty-medium.png
  src/assets/images/empty-movie.png
  src/assets/images/empty-small.png
  src/assets/index.ts
  src/components/cards/popcornTrendingCard/PopcornTrendingCard.style.ts
  src/components/cards/popcornTrendingCard/index.tsx
  src/components/checkBox/CheckBox.stories.tsx
  src/components/checkBox/index.tsx
  src/components/inputs/textArea/TextArea.style.ts
  src/components/items/movieItem/index.tsx
  src/components/items/popcornItem/PopcornItem.style.ts
  src/components/items/popcornItem/index.tsx
  src/components/rates/reviewRate/ReviewRate.style.ts
  src/components/rates/reviewRate/index.tsx
  src/components/rates/screeningRate/ScreeningRate.style.ts
  src/models/popcornParty/reponse/index.ts
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/BottomTabNavigator.style.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.style.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/SearchBottomSheet.style.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/signup/components/agreementBottomSheet/index.tsx
  src/types/ui.ts
Labels: Fix

#118 [FIX] svg, png 파일 충돌 해결
  src/assets/icons/gray-popcorn.svg
  src/assets/index.ts
Labels: Fix

#119 [FEAT] 마이페이지 리뷰 관리 API 연동
  src/apis/myPage/index.ts
  src/components/items/myManagementItem/index.tsx
  src/constants/review.ts
  src/models/myPage/response/index.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/manageReview/ManageReviewScreen.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/detail/components/detailMovie/DetailPopcorn.tsx
  src/types/myPage/index.tsx
  src/utils/getDate.ts
  src/utils/getReviewChips.ts
  src/utils/getWeekOfMonth.ts
Labels: Feature

#120 [FIX] 1차 QA 팝콘파티 API 수정
  src/components/items/movieItem/index.tsx
  src/hooks/mutaions/useMovieReviewMutation.ts
  src/hooks/mutaions/usePopcornPartyMutation.ts
  src/hooks/mutaions/useRecommendMovie.ts
  src/hooks/mutaions/useRecommendMovieMutation.ts
  src/models/popcornParty/reponse/index.ts
  src/models/popcornParty/request/index.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/home/components/voteNextPopcorn/index.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/popCornParty/writeReview/WriteReviewScreen.tsx
  src/types/popcornParty/index.ts
  src/utils/getMovieList.ts
Labels: Fix

#122 [FEAT] 애플 로그인 API 연동
  src/components/auth/apple/index.tsx
  src/components/auth/kakao/index.tsx
  src/hooks/mutaions/useUserMutation.ts
  src/models/auth/request/index.ts
  src/screens/login/LoginScreen.tsx
  src/screens/login/components/lookAround/LookAround.style.ts
  src/screens/login/components/lookAround/index.tsx
  src/screens/signup/SignupScreen.tsx
  src/screens/signup/components/agreementBottomSheet/index.tsx
  src/screens/signup/components/inputGenre/index.tsx
  src/stores/user.ts
  src/types/navigator.ts
  src/types/user.ts
Labels: Feature

#125 [FEAT] 로그아웃 기능 추가
  src/apis/auth/auth.ts
  src/apis/user/user.ts
  src/assets/icons/gray-popcorn.svg
  src/components/inputs/textArea/TextArea.style.ts
  src/components/pages/detailReviewPage/index.tsx
  src/components/pages/detailStatisticPage/index.tsx
  src/components/popup/Popup.style.ts
  src/components/popup/index.tsx
  src/components/select/Select.style.ts
  src/components/select/index.tsx
  src/hooks/mutaions/useUserMutation.ts
  src/models/auth/request/index.ts
  src/models/enums/user.ts
  src/models/screening/response/detailResponseDto.ts
  src/models/user/response/userResponseDto.ts
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/screening/kakaoSearch/KakaoSearchScreen.tsx
  src/services/localStorage/localStorage.ts
Labels: Feature

#126 [FEAT] 닉네임 중복체크 API 연동
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-1024.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-120 1.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-120.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-40 1.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-40.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-58.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-60 1.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-60.png
  ios/Youngduck/Images.xcassets/AppIcon.appiconset/logo-87.png
  src/apis/user/user.ts
  src/components/input/index.tsx
  src/hooks/mutaions/useUserMutation.ts
  src/hooks/useCheckNicknameDuplication.ts
  src/hooks/useFocus.ts
  src/models/user/response/userResponseDto.ts
  src/navigators/Navigator.tsx
  src/screens/myPage/changeNickname/ChangeNicknameScreen.tsx
  src/screens/signup/components/inputNickname/index.tsx
Labels: Feature

#128 [FEAT] 계정 탈퇴 API 연동
  src/components/select/index.tsx
  src/hooks/mutaions/useUserMutation.ts
  src/models/enums/user.ts
  src/screens/myPage/setting/screens/withdraw/WithdrawScreen.tsx
  src/utils/getQuitReason.ts
Labels: Feature

#136 [FEAT] 마이페이지 나의 스크리닝 API 연동
  src/apis/myPage/index.ts
  src/components/items/myManagementItem/index.tsx
  src/models/myPage/response/index.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/manageReview/ManageReviewScreen.tsx
  src/screens/myPage/manageScreening/ManageScreeningScreen.tsx
  src/screens/myPage/myScreening/MyScreeningScreen.tsx
  src/utils/getDate.ts
Labels: Feature

#137 [FIX] 이미지 업로드 변경된 API 연동
  package.json
  src/apis/image/image.ts
  src/hooks/mutaions/useScreeningMutation.ts
  src/models/image/request/index.ts
  src/screens/screening/writing/components/screeningGallery/index.tsx
  src/services/imagePicker.ts
  src/services/imageService.ts
  yarn.lock
Labels: Fix

#139 [FEAT] 유저 정보 API 연동
  package.json
  src/apis/user/user.ts
  src/components/chip/Chip.style.ts
  src/components/chip/index.tsx
  src/components/items/commentItem/index.tsx
  src/hooks/mutaions/useUserMutation.ts
  src/models/user/response/userResponseDto.ts
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/myPage/MyPageScreen.style.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/types/ui.ts
  src/utils/getProfile.ts
  yarn.lock
Labels: Feature

#143 [FIX] 마이페이지 item prop 수정
  firebase.json
  ios/Podfile.lock
  src/components/items/myManagementItem/MyManagementItem.style.ts
  src/components/items/myManagementItem/index.tsx
  src/models/myPage/response/index.ts
  src/screens/myPage/manageReview/ManageReviewScreen.tsx
  src/screens/myPage/manageScreening/ManageScreeningScreen.tsx
Labels: Fix

#145 [FEAT] pull to refresh 기능 추가
  src/apis/screening/review.ts
  src/components/container/defaultScrollContainer/index.tsx
  src/components/pages/detailInfoPage/index.tsx
  src/hooks/useInvalidateQueries.ts
  src/hooks/useRefresh.ts
  src/navigators/StackNavigator.tsx
  src/screens/popCornParty/home/PopcornPartyHomeScreen.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/screeningList/ScreeningList.tsx
  src/screens/screening/screeningList/components/screeningSearchList/index.tsx
  src/utils/wait.ts
Labels: Feature

#147 [FIX] 2차 스크리닝 QA 피드백 반영
  src/assets/icons/blue-tooltip.svg
  src/components/bottomButton/bottomBoxButton/BottomBoxButton.style.ts
  src/components/bottomButton/bottomBoxButton/index.tsx
  src/components/bottomButton/bottomOptionButton/BottomOptionButton.style.ts
  src/components/bottomButton/bottomOptionButton/index.tsx
  src/components/chip/index.tsx
  src/components/input/index.tsx
  src/components/inputs/buttonInput/index.tsx
  src/components/items/commentItem/index.tsx
  src/components/profile/index.tsx
  src/components/tooltip/Tooltip.style.ts
  src/components/tooltip/index.tsx
  src/hooks/useFocus.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/components/bottomDetailButton/index.tsx
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
  src/screens/screening/reviewWriting/tabs/ScreeningReview.style.ts
  src/screens/screening/reviewWriting/tabs/endReview/index.tsx
  src/screens/screening/reviewWriting/tabs/firstReview/index.tsx
  src/screens/screening/reviewWriting/tabs/selectReview/index.tsx
  src/screens/screening/writing/WritingScreen.style.ts
  src/screens/screening/writing/WritingScreen.tsx
Labels: Fix

#150 [FEAT] fcm api 연동
  src/App.tsx
  src/apis/fcm/alarm.ts
  src/models/fcm/request/fcmAlarmRequestDto.ts
  src/models/user/response/userResponseDto.ts
  src/navigators/bottomTabNavigator/index.tsx
  src/services/alarmService.ts
Labels: Feature

#152 [FIX] 3차 QA 이후 UI 수정
  src/components/bottomButton/bottomBoxButton/BottomBoxButton.style.ts
  src/components/container/defaultScrollContainer/index.tsx
  src/components/container/imageContentScrollContainer/index.tsx
  src/components/input/index.tsx
  src/components/items/myManagementItem/MyManagementItem.style.ts
  src/components/items/myManagementItem/index.tsx
  src/hooks/mutaions/useScreeningMutation.ts
  src/hooks/mutaions/useUserMutation.ts
  src/models/enums/user.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/myDetail/MyDetailScreen.tsx
  src/screens/signup/components/inputGenre/index.tsx
  src/styles/Input.style.ts
  src/types/signup/genre.ts
  src/utils/getQuitReason.ts
Labels: Fix

#155 [FIX] 스크리닝 페이지, 로그인 둘러보기 텍스트 변경
  src/App.tsx
  src/apis/popcornParty/index.ts
  src/apis/popcornParty/recommendList/recommendList.ts
  src/apis/screening/list.ts
  src/apis/screening/screening.ts
  src/assets/icons/chat.svg
  src/assets/icons/heart.svg
  src/components/items/screeningItem/index.tsx
  src/components/loginPopup/index.tsx
  src/components/popup/index.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/screening/home/HomeScreen.tsx
  src/screens/screening/home/components/reviewItem/index.tsx
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/screens/screening/screeningList/ScreeningList.tsx
  src/services/alarmService.ts
  src/utils/getDate.ts
Labels: Fix

#157 [FIX] 3차 QA 팝콘파티, 마이페이지 피드백 반영
  ios/Youngduck.xcodeproj/project.pbxproj
  src/apis/popcornParty/detail/detail.ts
  src/assets/svgIcons/index.tsx
  src/components/bottomButton/bottomOptionButton/BottomOptionButton.style.ts
  src/components/bottomSheet/index.tsx
  src/components/cards/popcornTrendingCard/index.tsx
  src/components/container/imageContentScrollContainer/index.tsx
  src/components/input/index.tsx
  src/components/inputs/customTextInput/CustomTextInput.style.ts
  src/components/inputs/customTextInput/index.tsx
  src/components/items/commentItem/index.tsx
  src/components/items/keywordItem/index.tsx
  src/components/items/myManagementItem/MyManagementItem.style.ts
  src/components/pages/detailInfoPage/index.tsx
  src/components/popcornKeyword/PopcornKeyword.style.ts
  src/components/popcornKeyword/index.tsx
  src/components/rates/screeningRate/index.tsx
  src/hooks/mutaions/usePopcornPartyMutation.ts
  src/hooks/useHandleInputNickname.ts
  src/models/myPage/response/index.ts
  src/models/popcornParty/reponse/index.ts
  src/navigators/StackNavigator.tsx
  src/screens/myPage/changeNickname/ChangeNicknameScreen.tsx
  src/screens/myPage/manageReview/ManageReviewScreen.tsx
  src/screens/myPage/manageReview/dummy.ts
  src/screens/myPage/manageScreening/dummy.ts
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/myPage/setting/screens/withdraw/WithdrawScreen.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/detail/components/detailBottomButtons/DetailBottomButtons.tsx
  src/screens/popCornParty/detail/popcornPartyDetailScreen.style.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.style.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/popCornParty/writeRecommand/hook/useSearchMovieMutation.ts
  src/screens/popCornParty/writeReview/WriteReviewScreen.style.ts
  src/screens/popCornParty/writeReview/WriteReviewScreen.tsx
  src/screens/popCornParty/writeReview/reviewTarget/ReviewTarget.style.ts
  src/screens/popCornParty/writeReview/reviewTarget/index.tsx
  src/screens/popCornParty/writeReview/startReview/index.tsx
  src/screens/signup/components/inputNickname/InputNickname.style.ts
  src/screens/signup/components/inputNickname/index.tsx
  src/screens/signupComplete/SignupCompleteScreen.style.ts
Labels: Fix

#163 [UI] android 앱 아이콘, 이름, 스플래시 화면 적용
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
  app.json
Labels: UI

#162 [FEAT] textInput 유효성 검사 로직 추가
  package.json
  src/components/dateRangeInput/index.tsx
  src/components/input/index.tsx
  src/components/inputs/buttonInput/index.tsx
  src/components/inputs/textArea/TextArea.style.ts
  src/components/inputs/textArea/index.tsx
  src/components/pages/detailStatisticPage/index.tsx
  src/components/searchBar/index.tsx
  src/components/select/index.tsx
  src/components/textInput/index.tsx
  src/components/timeInput/index.tsx
  src/hooks/useFocus.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.style.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/screening/screeningList/ScreeningList.tsx
  src/screens/screening/writing/WritingScreen.style.ts
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/screening/writing/hooks/useHandleInput.ts
  src/styles/Input.style.ts
  src/utils/checkValue.ts
  yarn.lock
Labels: Feature

#166 [FEAT] 알림 foreground 설정
  src/App.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/services/alarmService.ts
Labels: Feature

#167 [FIX] 스크리닝 상세, 리뷰, 목록 수정
  src/assets/svgIcons/index.tsx
  src/components/bottomButton/bottomBoxButton/BottomBoxButton.style.ts
  src/components/bottomButton/bottomOptionButton/BottomOptionButton.style.ts
  src/components/buttonGroups/selectMultipleButtons/SelectMultipleButtons.style.ts
  src/components/buttonGroups/selectMultipleButtons/index.tsx
  src/models/enums/category.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/SearchBottomSheet.style.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/screening/detail/DetailScreen.style.ts
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/home/components/weeklyScreening/WeeklyScreening.style.ts
  src/screens/screening/home/components/weeklyScreening/index.tsx
  src/screens/screening/screeningList/ScreeningList.tsx
  src/screens/screening/screeningList/components/screeningSearchList/index.tsx
Labels: Fix

#170 [FIX] 배포 전 수정되지 않은 UI 작업
  src/components/container/defaultContainer/DefaultContainer.style.ts
  src/components/pages/detailReviewPage/DetailReviewPage.style.ts
  src/components/pages/detailReviewPage/index.tsx
  src/screens/popCornParty/home/dummy.ts
  src/screens/popCornParty/recommandList/dummy.ts
  src/screens/screening/reviewWriting/ReviewWritingScreen.tsx
  src/screens/screening/reviewWriting/tabs/ScreeningReview.style.ts
Labels: Fix

#171 [FEAT] 웹뷰에서 인앱브라우저로 변경
  android/build.gradle
  package.json
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/hooks/useScreeningType.ts
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
  src/services/inappBrowser.ts
  src/stores/webview.ts
  src/types/navigator.ts
  yarn.lock
Labels: Feature

#173 [FIX] 스크리닝 홈 디자인 변경
  src/screens/screening/home/components/reviewItem/index.tsx
Labels: Fix

#175 [FIX] 설정 인앱브라우저로 연결
  package.json
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/myPage/setting/screens/agreement/AgreementScreen.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/hooks/useScreeningType.ts
  src/screens/screening/myDetail/MyDetailScreen.tsx
  src/types/navigator.ts
  yarn.lock
Labels: Fix

#178 [FIX] 웹뷰 uri 가공 로직 추가
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  package.json
  src/constants/stackScreens.ts
  src/navigators/StackNavigator.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/myPage/setting/screens/agreement/AgreementScreen.tsx
  src/screens/screening/detail/DetailScreen.tsx
  src/screens/screening/detail/hooks/useScreeningType.ts
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
  src/services/inappBrowser.ts
  src/stores/webview.ts
  src/types/navigator.ts
  yarn.lock
Labels: Fix

#180 [FIX] 출시 전 미흡한 UI 수정
  android/gradlew
  ios/Podfile.lock
  src/components/buttonGroups/selectMultipleButtons/SelectMultipleButtons.style.ts
  src/components/buttonGroups/selectMultipleButtons/index.tsx
  src/components/cards/screeningRateCard/index.tsx
  src/components/inputs/customTextInput/index.tsx
  src/constants/review.ts
  src/hooks/useHandleAgreement.ts
  src/screens/myPage/MyPageScreen.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/SearchBottomSheet.style.ts
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
  src/screens/popCornParty/writeReview/selectReview/index.tsx
  src/screens/screening/reviewWriting/tabs/selectReview/index.tsx
  src/screens/screening/writing/WritingScreen.style.ts
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/signup/components/agreementBottomSheet/Agreement.tsx
  src/screens/signup/components/agreementBottomSheet/index.tsx
  src/types/signup/agreement.ts
Labels: Fix

#184 [FIX] 1차 심사 리젝 반영 수정
  ios/Youngduck.xcodeproj/project.pbxproj
  src/assets/svgIcons/index.tsx
  src/components/topBar/cancelTopBar/CancelTopBar.style.ts
  src/components/topBar/cancelTopBar/index.tsx
  src/navigators/StackNavigator.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/myPage/setting/screens/agreement/AgreementScreen.tsx
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/signup/components/agreementBottomSheet/Agreement.tsx
  src/types/navigator.ts
Labels: Fix

#186 Fix/#185
  src/assets/svgIcons/index.tsx
  src/components/topBar/backCancelTopBar/index.tsx
  src/components/topBar/backTitleTopBar/index.tsx
  src/components/topBar/backTopBar/BackTopBar.stories.tsx
  src/components/topBar/backTopBar/index.tsx
  src/components/topBar/titleCenterTopBar/index.tsx
  src/screens/popCornParty/writeRecommand/components/searchBottomSheet/index.tsx
Labels: Fix

#188 [FIX] 배포 후 자잘한 오류 해결
  src/components/popup/index.tsx
  src/components/rates/popcornRate/index.tsx
  src/components/topBar/backTitleTopBar/index.tsx
  src/components/typography/index.tsx
  src/hooks/useHandleInputNickname.ts
  src/screens/login/LoginScreen.tsx
  src/screens/myPage/manageScreening/ManageScreeningScreen.tsx
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/home/components/trendingMovie/index.tsx
  src/screens/popCornParty/home/components/trendingPopcorn/index.tsx
  src/screens/popCornParty/home/components/voteNextPopcorn/index.tsx
  src/screens/popCornParty/recommandList/RecommandListScreen.tsx
Labels: Fix

#191 [FIX] textInput, textArea 유효성 검증 로직 수정
  android/app/build.gradle
  src/components/dateRangeInput/index.tsx
  src/components/inputs/textArea/index.tsx
  src/components/textInput/index.tsx
  src/hooks/useFocus.ts
  src/hooks/useText.ts
  src/screens/popCornParty/detail/PopcornPartyDetailScreen.tsx
  src/screens/popCornParty/detail/popcornPartyDetailScreen.style.ts
  src/screens/popCornParty/writeRecommand/WriteRecommandScreen.tsx
  src/screens/popCornParty/writeReview/WriteReviewScreen.tsx
  src/screens/popCornParty/writeReview/selectReview/index.tsx
  src/screens/popCornParty/writeReview/startReview/index.tsx
  src/screens/screening/reviewWriting/tabs/ScreeningReview.style.ts
  src/screens/screening/writing/WritingScreen.tsx
  src/screens/screening/writing/hooks/useHandleInput.ts
  src/utils/checkValue.ts
Labels: Fix

#193 [FIX] 2차 배포 후 생긴 수정 사항
  src/components/textInput/index.tsx
  src/navigators/bottomTabNavigator/index.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/popCornParty/detail/popcornPartyDetailScreen.style.ts
  src/screens/screening/detailWebview/DetailWebviewScreen.tsx
Labels: Fix

#195 [FIX] 버전 1.0.6 UI 수정 사항
  .github/ISSUE_TEMPLATE/bug-issue-template.md
  .github/ISSUE_TEMPLATE/feature-issue-template.md
  .github/ISSUE_TEMPLATE/fix-issue-template.md
  .github/ISSUE_TEMPLATE/performance-issue-template.md
  .github/ISSUE_TEMPLATE/refactor-issue-template.md
  .github/ISSUE_TEMPLATE/rename-issue-template.md
  .github/ISSUE_TEMPLATE/ui-issue-template.md
  ios/Youngduck.xcodeproj/project.pbxproj
  src/components/inputs/customTextInput/index.tsx
  src/components/pages/detailStatisticPage/DetailStatisticPage.style.ts
  src/hooks/mutaions/useScreeningMutation.ts
  src/hooks/useHandleInputNickname.ts
  src/screens/myPage/changeNickname/ChangeNicknameScreen.tsx
  src/screens/myPage/setting/SettingScreen.tsx
  src/screens/signup/components/inputNickname/index.tsx
  src/styles/Input.style.ts
Labels: Fix

#197 [FEAT] 로그인, 회원가입, 로그인 둘러보기 스택 reset
  android/app/build.gradle
  src/hooks/mutaions/useUserMutation.ts
  src/navigators/StackNavigator.tsx
  src/screens/login/components/lookAround/index.tsx
  src/screens/signupComplete/SIgnupCompleteScreen.tsx
  src/styles/Input.style.ts
Labels: Feature

#202 [FIX] 상세 스크린에서 사용되는 스크롤 컨테이너 수정
  src/components/container/imageContentScrollContainer/index.tsx
Labels: Fix
